## Lecture: Thinking Data
### In this lecture we are going to learn to think in terms of data & try to answer some important questions as an AI Engineer/ Data Scientist:
- What is clean & structured data?
- How to get insights from data?
- How to use data to improve products & build features (eg - productrecommendations)?

In [4]:
import json
import math
a = 12
b = 23
sum = (a+b)
print(sum)

35


In [81]:
#function to load the data
def load_data(filename):
    with open(filename, "r") as f:
        data = json.load(f)
    return data 

In [82]:
data = load_data("amazon_store_data.json")

In [98]:
#function to clean the data
def clean_data(data):
    text_to_num = {"one" : 1, "two" : 2, "three" : 3, "four": 4, "five": 5}
    
    unique_users = set()
    cleaned_data = []
    
    for user in data:
        #clean rating - consistent typing
        raw_rating = str(user['rating']).strip().lower()
        if(raw_rating in text_to_num):
            raw_rating = text_to_num[raw_rating]
        user['rating'] = raw_rating

        #handle missing values
        raw_age = user.get("age")
        if(raw_age == None):
            user["age"] = None

        #handle duplicate values - deduplication
        if(user['name'].strip() in unique_users):
            continue
        unique_users.add(user['name'])
        cleaned_data.append(user)
        
    return cleaned_data
        

In [99]:
data = clean_data(data)
print(data, len(data))

[{'name': 'Alice', 'rating': '5', 'feedback': 'Great product!!', 'age': '25'}, {'name': 'Bob', 'rating': '4', 'feedback': 'ok but late Delivery', 'age': '30'}, {'name': ' Charlie', 'rating': '2', 'feedback': 'BAD EXPERIENCE ', 'age': None}, {'name': 'Diana', 'feedback': 'Loved it!', 'rating': '5', 'age': '28'}, {'name': 'Eve', 'rating': '3.5', 'feedback': 'Average - could be better', 'age': '20'}] 5


In [106]:
#function to get insights from data
def get_insights(data):
    #avg rating
    tot_ratings = 0
    for user in data:
        tot_ratings += float(user['rating'])
    
    print(f"average product rating = {tot_ratings/len(data)}")

    #percentage users with poor rating
    poor_ratings = 0
    for user in data:
        if(float(user['rating']) < 3.0):
            poor_ratings += 1
    
    print(f"% users with poor rating = {poor_ratings/len(data)*100}%")

In [107]:
get_insights(data)

average product rating = 3.9
% users with poor rating = 20.0%


In [114]:
#product recommendation feature
def get_recommendations(data):
    recommendations = []
    
    for user in data:
        curr_recomm = {}
        curr_recomm['name'] = user['name']
        if(float(user['rating']) >= 4):
            curr_recomm['brand'] = "Apple"
        else:
            curr_recomm['brand'] = "Samsung"

        recommendations.append(curr_recomm)
    
    return recommendations
        

In [115]:
recommendations = get_recommendations(data)
print(recommendations)

[{'name': 'Alice', 'brand': 'Apple'}, {'name': 'Bob', 'brand': 'Apple'}, {'name': ' Charlie', 'brand': 'Samsung'}, {'name': 'Diana', 'brand': 'Apple'}, {'name': 'Eve', 'brand': 'Samsung'}]


In [3]:
import numpy as np
lin_arr = np.linspace(0, 1, 5) 
print(lin_arr)
identity = np.eye(3)
print(identity)

[0.   0.25 0.5  0.75 1.  ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
np.array([1,2,3]).ndim        # 1 -> simple line
np.array([[1,2,3],[4,5,6]]).ndim  # 2 -> grid/table

2

In [2]:
import numpy as np
arr = np.arange(1, 13)   # [1 2 3 ... 12]
reshaped = arr.reshape(3, 4)   # 3 rows, 4 columns
print(reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
flat = reshaped.flatten()  # wapas 1D mein

In [4]:
print(flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [1]:
num1 = input("Enter first number: ")
num2 = input("Enter second number: ")
a = int(num1)
b = int(num2)
add = a + b
sub = a - b
mul = a * b
div = a // b
mod = a % b
power = a ** b
x = float(num1)
y = float(num2)
float_div = x / y

print(f"Add: {add}  {type(add)}")
print(f"Sub: {sub}  {type(sub)}")
print(f"Mul: {mul}  {type(mul)}")
print(f"Div: {div}  {type(div)}")
print(f"Mod: {mod}  {type(mod)}")
print(f"Pow: {power}  {type(power)}")
print(f"Float Div: {float_div}  {type(float_div)}")

 


Enter first number:  12
Enter second number:  5


Add: 17  <class 'int'>
Sub: 7  <class 'int'>
Mul: 60  <class 'int'>
Div: 2  <class 'int'>
Mod: 2  <class 'int'>
Pow: 248832  <class 'int'>
Float Div: 2.4  <class 'float'>


In [1]:
name = input("Enter your name: ")
age = int(input("Enter your age: "))
course = input("Enter your course: ")
marks = float(input("Enter your marks: "))
city = input("Enter your city: ")

if marks >= 90:
    grade = "A"
elif marks >= 75:
    grade = "B"
elif marks >= 60:
    grade = "C"
else:
    grade = "D"

print("=" * 40)
print("STUDENT PROFILE")
print("=" * 40)
print(f"Name:{name}")
print(f"Age:{age}")
print(f"Course:{course}")
print(f"Marks:{marks}")
print(f"Grade:{grade}")
print(f"City:{city}")
print("=" * 40)


Enter your name:  Manjul Nath Sonkar
Enter your age:  21
Enter your course:  Data Annotation
Enter your marks:  89
Enter your city:  Gorakhpur


STUDENT PROFILE
Name:Manjul Nath Sonkar
Age:21
Course:Data Annotation
Marks:89.0
Grade:B
City:Gorakhpur
